CREATE DATABASE IF NOT EXISTS auth_project
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE auth_project;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    gmail VARCHAR(254) NOT NULL,
    phone CHAR(11) NOT NULL,
    username VARCHAR(10) NOT NULL,
    verification_code CHAR(4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY users_phone_unique (phone)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
